

/*
 *
 * Avro schema definition 
 *
 */


package streaming;

public class SchemaDefinition{

    public static final String AVRO_SCHEMA_OUT =
            "{"
            + "\"type\":\"record\","
            + "\"name\":\"testout\","
            + "\"fields\":["
            + "  {\"name\":\"out_1_field_1\",\"type\":\"string\" },"
            + "  {\"name\":\"out_1_field_2\",\"type\":\"string\" },"
            + "  {\"name\":\"out_1_field_3\",\"type\":\"string\" },"
            + "  {\"name\":\"out_1_field_4\",\"type\":\"string\" },"
            + "  {\"name\":\"out_1_field_5\",\"type\":\"string\" },"
            + "  {\"name\":\"out_1_field_6\",\"type\":\"string\" },"
            + "  {\"name\":\"out_1_field_7\",\"type\":\"string\" },"
            + "  {\"name\":\"out_1_field_8\",\"type\":\"string\" },"
            + "  {\"name\":\"out_1_field_9\",\"type\":\"string\" },"
            + "  {\"name\":\"out_1_field_0\",\"type\":\"string\" }"
            + "]}";

    public static final String AVRO_SCHEMA_TEST =
            "{"
            + "\"type\":\"record\","
            + "\"name\":\"test\","
            + "\"fields\":["
            + "  {\"name\":\"test_1_field_1\",\"type\":\"string\" },"
            + "  {\"name\":\"test_1_field_2\",\"type\":\"string\" },"
            + "  {\"name\":\"test_1_field_3\",\"type\":\"string\" },"
            + "  {\"name\":\"test_1_field_4\",\"type\":\"string\" },"
            + "  {\"name\":\"test_1_field_5\",\"type\":\"string\" },"
            + "  {\"name\":\"test_1_field_6\",\"type\":\"string\" },"
            + "  {\"name\":\"test_1_field_7\",\"type\":\"string\" },"
            + "  {\"name\":\"test_1_field_8\",\"type\":\"string\" },"
            + "  {\"name\":\"test_1_field_9\",\"type\":\"string\" },"
            + "  {\"name\":\"test_1_field_0\",\"type\":\"string\" }"
            + "]}";

    public static final String AVRO_SCHEMA_RBTRAN =
        "{"
        + "\"type\":\"record\","
        + "\"name\":\"rbtran\","
        + "\"fields\":["
		+ "  { \"name\":\"WORKFLOW_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"RECORD_TYPE_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"DATA_SPECIFICATION_VERSION_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"CLIENT_XID\",\"type\":\"string\" },"
		+ "  { \"name\":\"RCD_CRT_DTTM\",\"type\":\"string\" },"
		+ "  { \"name\":\"RCD_CRT_DTTM_D1\",\"type\":\"string\" },"
		+ "  { \"name\":\"RCD_CRT_DTTM_D2\",\"type\":\"string\" },"
		+ "  { \"name\":\"GMT_OFFSET\",\"type\":\"string\" },"
		+ "  { \"name\":\"CUSTOMER_XID\",\"type\":\"string\" },"
		+ "  { \"name\":\"ACCOUNT_REFERENCE_XID\",\"type\":\"string\" },"
		+ "  { \"name\":\"EXTERNAL_TRANSACTION_XID\",\"type\":\"string\" },"
		+ "  { \"name\":\"DEPOSIT_WITHDRAWAL_XFLG\",\"type\":\"string\" },"
		+ "  { \"name\":\"PAYMENT_ORDER_XFLG\",\"type\":\"string\" },"
		+ "  { \"name\":\"DEBIT_CUSTOMER_XID\",\"type\":\"string\" },"
		+ "  { \"name\":\"DEBIT_ACCOUNT_NUM\",\"type\":\"string\" },"
		+ "  { \"name\":\"DEBIT_ACCOUNT_BANK_XID\",\"type\":\"string\" },"
		+ "  { \"name\":\"DEBIT_ACCOUNT_BRANCH_XID\",\"type\":\"string\" },"
		+ "  { \"name\":\"DEBIT_ACCOUNT_SORT_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"DEBIT_ACCOUNT_COUNTRY_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"DEBIT_SEGMENT_XID\",\"type\":\"string\" },"
		+ "  { \"name\":\"DEBIT_SEGMENT_LEVEL_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"DEBIT_AMT\",\"type\":\"string\" },"
		+ "  { \"name\":\"DEBIT_CURRENCY_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"DEBIT_DT\",\"type\":\"string\" },"
		+ "  { \"name\":\"DEBIT_PAYER_NAME\",\"type\":\"string\" },"
		+ "  { \"name\":\"DEBIT_MESSAGE\",\"type\":\"string\" },"
		+ "  { \"name\":\"CREDIT_CUSTOMER_XID\",\"type\":\"string\" },"
		+ "  { \"name\":\"CREDIT_ACCOUNT_NUM\",\"type\":\"string\" },"
		+ "  { \"name\":\"CREDIT_ACCOUNT_BANK_XID\",\"type\":\"string\" },"
		+ "  { \"name\":\"CREDIT_ACCOUNT_BRANCH_XID\",\"type\":\"string\" },"
		+ "  { \"name\":\"CREDIT_ACCOUNT_SORT_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"CREDIT_ACCOUNT_COUNTRY_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"CREDIT_SEGMENT_XID\",\"type\":\"string\" },"
		+ "  { \"name\":\"CREDIT_SEGMENT_LEVEL_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"CREDIT_AMT\",\"type\":\"string\" },"
		+ "  { \"name\":\"CREDIT_CURRENCY_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"CREDIT_DT\",\"type\":\"string\" },"
		+ "  { \"name\":\"CREDIT_PAYER_NAME\",\"type\":\"string\" },"
		+ "  { \"name\":\"CREDIT_MESSAGE\",\"type\":\"string\" },"
		+ "  { \"name\":\"EXCHANGE_RATIO\",\"type\":\"string\" },"
		+ "  { \"name\":\"TRANSACTION_XID\",\"type\":\"string\" },"
		+ "  { \"name\":\"TRANSACTION_DTTM\",\"type\":\"string\" },"
		+ "  { \"name\":\"TRANSACTION_DTTM_D1\",\"type\":\"string\" },"
		+ "  { \"name\":\"TRANSACTION_DTTM_D2\",\"type\":\"string\" },"
		+ "  { \"name\":\"TRANSACTION_AMT\",\"type\":\"string\" },"
		+ "  { \"name\":\"TRANSACTION_ISO_CURRENCY_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"TRAN_ISO_CURRENCY_CNVRSN_RATIO\",\"type\":\"string\" },"
		+ "  { \"name\":\"TRANSACTION_ADDR_LINE_1_STRG\",\"type\":\"string\" },"
		+ "  { \"name\":\"TRANSACTION_POSTAL_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"TRANSACTION_CITY_NAME\",\"type\":\"string\" },"
		+ "  { \"name\":\"TRANS_COUNTRY_REGION_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"TRANSACTION_COUNTRY_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"TRANSACTION_TYPE_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"ACCESS_CHANNEL_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"PROCESSING_CHANNEL_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"PROCESSING_TYPE_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"INTERNATIONAL_IND_XFLG\",\"type\":\"string\" },"
		+ "  { \"name\":\"DEVICE_XID\",\"type\":\"string\" },"
		+ "  { \"name\":\"AUTHENTICATION_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"SERVICE_REPRESENTATIVE_XID\",\"type\":\"string\" },"
		+ "  { \"name\":\"ON_US_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"DECISION_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"TRAN_REVERSAL_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"TRANSACTION_REVERSED_DTTM\",\"type\":\"string\" },"
		+ "  { \"name\":\"TRANSACTION_REVERSED_DTTM_D1\",\"type\":\"string\" },"
		+ "  { \"name\":\"TRANS_REVERSED_REASON_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"RECURRING_AUTHORIZATION_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"RECURRING_AUTHZN_EXPIRATION_DT\",\"type\":\"string\" },"
		+ "  { \"name\":\"MODEL_CONTROL_1_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"MODEL_CONTROL_2_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"MODEL_CONTROL_3_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"MODEL_CONTROL_4_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_INDICATOR_1_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_INDICATOR_2_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_INDICATOR_3_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_INDICATOR_4_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_INDICATOR_5_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER1_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER2_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER3_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER4_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER5_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_DATA_1_STRG\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_DATA_2_STRG\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_DATA_3_STRG\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_DATA_4_STRG\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_DATA_5_STRG\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_DATA_6_NUM\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_DATA_7_STRG\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_DATA_8_STRG\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_DATA_9_STRG\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_DATA_10_STRG\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_DATA_11_STRG\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_DATA_12_STRG\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_DATA_13_STRG\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_DATA_14_STRG\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_DATA_15_STRG\",\"type\":\"string\" },"
		+ "  { \"name\":\"RESERVED_01\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_INDICATOR_6_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_INDICATOR_7_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER06_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER07_XCD\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_DATA_16_STRG\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_DATA_17_STRG\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_DATA_18_STRG\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_DATA_19_STRG\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_DATA_20_STRG\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_DATA_21_STRG\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_DATA_22_STRG\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_DATA_23_STRG\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_DATA_24_STRG\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_DATA_25_STRG\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_DATA_26_STRG\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_DATA_27_STRG\",\"type\":\"string\" },"
		+ "  { \"name\":\"USER_DATA_28_STRG\",\"type\":\"string\" },"
		+ "  { \"name\":\"SESSION_XID\",\"type\":\"string\" }"
        + "]}";

    public static final String AVRO_SCHEMA_AIS =
        "{"
        + "\"type\":\"record\","
        + "\"name\":\"AIS\","
        + "\"fields\":["
        + "  { \"name\":\"fico_field_1\", \"type\":\"string\" }"
        + "]}";

    public static final String AVRO_SCHEMA_BIS =
        "{"
        + "\"type\":\"record\","
        + "\"name\":\"BIS\","
        + "\"fields\":["
        + "  { \"name\":\"fico_field_1\", \"type\":\"string\" }"
        + "]}";

    public static final String AVRO_SCHEMA_CIS =
        "{"
        + "\"type\":\"record\","
        + "\"name\":\"CIS\","
        + "\"fields\":["
        + "  { \"name\":\"fico_field_1\", \"type\":\"string\" }"
        + "]}";

    public static final String AVRO_SCHEMA_NMON =
        "{"
        + "\"type\":\"record\","
        + "\"name\":\"NMON\","
        + "\"fields\":["
        + "  { \"name\":\"fico_field_1\", \"type\":\"string\" }"
        + "]}";



    public static final String AVRO_SCHEMA_f2441em =
            "{"
            + "\"type\":\"record\","
            + "\"name\":\"f2441em\","
            + "\"fields\":["
            + "  { \"name\":\"f2441hm_PARTITION_OF_TABLE\", \"type\":{\"type\":\"fixed\", \"name\":\"n1\",  \"size\":2} },"
            + "  { \"name\":\"f2441em_ACCOUNT_OF_PAYER\", \"type\":{\"type\":\"fixed\", \"name\":\"n2\",  \"size\":35} },"
            + "  { \"name\":\"f2441em_PRESENT_TIMESTAMP\", \"type\":{\"type\":\"fixed\", \"name\":\"n3\",  \"size\":20} },"
            + "  { \"name\":\"f2441em_OWNER_APPLICATION\", \"type\":{\"type\":\"fixed\", \"name\":\"n4\",  \"size\":4} },"
            + "  { \"name\":\"f2441em_APPL_SPECIFIER\", \"type\":{\"type\":\"fixed\", \"name\":\"n5\",  \"size\":1} },"
            + "  { \"name\":\"f2441em_ORIGIN_OF_PAYMENT\", \"type\":{\"type\":\"fixed\", \"name\":\"n6\",  \"size\":3} },"
            + "  { \"name\":\"f2441em_STATUS_OF_PAYMENT\", \"type\":{\"type\":\"fixed\", \"name\":\"n7\",  \"size\":1} },"
            + "  { \"name\":\"f2441em_STATUS_SPECIFIER\", \"type\":{\"type\":\"fixed\", \"name\":\"n8\",  \"size\":2} },"
            + "  { \"name\":\"f2441em_STATUS_DATE\", \"type\":{\"type\":\"fixed\", \"name\":\"n9\",  \"size\":8} },"
            + "  { \"name\":\"f2441em_ACCOUNT_OF_PAYEE\", \"type\":{\"type\":\"fixed\", \"name\":\"n10\",  \"size\":35} },"
            + "  { \"name\":\"f2441em_NAME_OF_PAYEE\", \"type\":{\"type\":\"fixed\", \"name\":\"n11\",  \"size\":30} },"
            + "  { \"name\":\"f2441em_DUE_DATE\", \"type\":{\"type\":\"fixed\", \"name\":\"n12\",  \"size\":8} },"
            + "  { \"name\":\"f2441em_DATE_OF_PAYMENT\", \"type\":{\"type\":\"fixed\", \"name\":\"n13\",  \"size\":8} },"
            + "  { \"name\":\"f2441em_AMOUNT_OF_PAYMENT\", \"type\":{\"type\":\"fixed\", \"name\":\"h14o1\",  \"size\":9} },"
            + "  { \"name\":\"f2441em_CURRENCY_CODE\", \"type\":{\"type\":\"fixed\", \"name\":\"n15\",  \"size\":3} },"
            + "  { \"name\":\"f2441em_EMU_INDICATOR\", \"type\":{\"type\":\"fixed\", \"name\":\"n16\",  \"size\":1} },"
            + "  { \"name\":\"f2441em_CUSTOM_MODIF_RIGHT\", \"type\":{\"type\":\"fixed\", \"name\":\"n17\",  \"size\":1} },"
            + "  { \"name\":\"f2441em_SOLO_USER_ID\", \"type\":{\"type\":\"fixed\", \"name\":\"n18\",  \"size\":16} },"
            + "  { \"name\":\"f2441em_DISPOSAL_TYPE\", \"type\":{\"type\":\"fixed\", \"name\":\"n19\",  \"size\":1} },"
            + "  { \"name\":\"f2441em_REPEATING_RULE\", \"type\":{\"type\":\"fixed\", \"name\":\"n20\",  \"size\":1} },"
            + "  { \"name\":\"f2441em_PCS_OF_REPEATS\", \"type\":{\"type\":\"fixed\", \"name\":\"h21o0\",  \"size\":3} },"
            + "  { \"name\":\"f2441em_INVOICING_INFO\", \"type\":{\"type\":\"fixed\", \"name\":\"n22\",  \"size\":1} },"
            + "  { \"name\":\"f2441em_ORIGINAL_KEY\", \"type\":{\"type\":\"fixed\", \"name\":\"n23\",  \"size\":55} },"
            + "  { \"name\":\"f2441em_PAYMENT_SUBJECT\", \"type\":{\"type\":\"fixed\", \"name\":\"n24\",  \"size\":3} },"
            + "  { \"name\":\"f2441em_ARCHIV_SLIP_NUMBER\", \"type\":{\"type\":\"fixed\", \"name\":\"n25\",  \"size\":20} },"
            + "  { \"name\":\"f2441em_UPDATE_TIME_STAMP\", \"type\":{\"type\":\"fixed\", \"name\":\"n26\",  \"size\":14} },"
            + "  { \"name\":\"f2441em_REFERENCE_NUMBER\", \"type\":{\"type\":\"fixed\", \"name\":\"n27\",  \"size\":20} },"
            + "  { \"name\":\"f2441em_MESSAGE_INFO\", \"type\":{\"type\":\"fixed\", \"name\":\"n28\",  \"size\":1} },"
            + "  { \"name\":\"f2441em_DEBIT_RETURN_CODE\", \"type\":{\"type\":\"fixed\", \"name\":\"n29\",  \"size\":8} },"
            + "  { \"name\":\"f2441em_DEBIT_ARCHIV_NUMB\", \"type\":{\"type\":\"fixed\", \"name\":\"n30\",  \"size\":20} },"
            + "  { \"name\":\"f2441em_CREDIT_RETURN_CODE\", \"type\":{\"type\":\"fixed\", \"name\":\"n31\",  \"size\":8} },"
            + "  { \"name\":\"f2441em_CREDIT_ARCHIV_NUMB\", \"type\":{\"type\":\"fixed\", \"name\":\"n32\",  \"size\":20} },"
            + "  { \"name\":\"f2441em_PAYEE_ACCOUNT_TYPE\", \"type\":{\"type\":\"fixed\", \"name\":\"n33\",  \"size\":1} },"
            + "  { \"name\":\"f2441em_PAYEE_NAME_ORIGIN\", \"type\":{\"type\":\"fixed\", \"name\":\"n34\",  \"size\":1} },"
            + "  { \"name\":\"f2441em_REPEATING_DAYS\", \"type\":{\"type\":\"fixed\", \"name\":\"n35\",  \"size\":24} },"
            + "  { \"name\":\"f2441em_REPEATING_PERIOD\", \"type\":{\"type\":\"fixed\", \"name\":\"h36o0\",  \"size\":2} },"
            + "  { \"name\":\"f2441em_END_DATE_OF_REPEAT\", \"type\":{\"type\":\"fixed\", \"name\":\"n37\",  \"size\":8} },"
            + "  { \"name\":\"f2441em_REPEAT_CHANGE_INFO\", \"type\":{\"type\":\"fixed\", \"name\":\"n38\",  \"size\":1} },"
            + "  { \"name\":\"f2441em_INHERITANCE_INFO\", \"type\":{\"type\":\"fixed\", \"name\":\"n39\",  \"size\":1} },"
            + "  { \"name\":\"f2441em_BALANCE_OFFICE\", \"type\":{\"type\":\"fixed\", \"name\":\"n40\",  \"size\":4} },"
            + "  { \"name\":\"f2441em_ACCT_RESP_OFFICE\", \"type\":{\"type\":\"fixed\", \"name\":\"n41\",  \"size\":4} },"
            + "  { \"name\":\"f2441em_DUE_DATE_TYPE\", \"type\":{\"type\":\"fixed\", \"name\":\"n42\",  \"size\":1} },"
            + "  { \"name\":\"f2441em_PAYERS_RECEIPT\", \"type\":{\"type\":\"fixed\", \"name\":\"n43\",  \"size\":1} },"
            + "  { \"name\":\"f2441em_PAYEES_RECEIPT\", \"type\":{\"type\":\"fixed\", \"name\":\"n44\",  \"size\":1} },"
            + "  { \"name\":\"f2441em_USERS_CARD_NUMBER\", \"type\":{\"type\":\"fixed\", \"name\":\"n45\",  \"size\":19} },"
            + "  { \"name\":\"f2441em_CUSTOMER_ROLE\", \"type\":{\"type\":\"fixed\", \"name\":\"n46\",  \"size\":1} },"
            + "  { \"name\":\"f2441em_CONTROL_CODE\", \"type\":{\"type\":\"fixed\", \"name\":\"n47\",  \"size\":1} },"
            + "  { \"name\":\"f2441em_SOLO_AGR_TYPE\", \"type\":{\"type\":\"fixed\", \"name\":\"n48\",  \"size\":1} },"
            + "  { \"name\":\"f2441em_AMOUNT_LIMIT_CHECK\", \"type\":{\"type\":\"fixed\", \"name\":\"n49\",  \"size\":1} },"
            + "  { \"name\":\"f2441em_DEBTOR_ID\", \"type\":{\"type\":\"fixed\", \"name\":\"n50\",  \"size\":35} },"
            + "  { \"name\":\"f2441em_DEBTOR_ID_CODE\", \"type\":{\"type\":\"fixed\", \"name\":\"n51\",  \"size\":20} },"
            + "  { \"name\":\"f2441em_CREDITOR_BIC\", \"type\":{\"type\":\"fixed\", \"name\":\"n52\",  \"size\":11} },"
            + "  { \"name\":\"f2441em_CREDITOR_NAME\", \"type\":{\"type\":\"fixed\", \"name\":\"n53\",  \"size\":70} },"
            + "  { \"name\":\"f2441em_END_TO_END_ID\", \"type\":{\"type\":\"fixed\", \"name\":\"n54\",  \"size\":35} },"
            + "  { \"name\":\"f2441em_ULTIMATE_CREDITOR\", \"type\":{\"type\":\"fixed\", \"name\":\"n55\",  \"size\":70} },"
            + "  { \"name\":\"f2441em_ULTIMATE_DEBTOR\", \"type\":{\"type\":\"fixed\", \"name\":\"n56\",  \"size\":70} },"
            + "  { \"name\":\"f2441em_UR_TEXT_CODE\", \"type\":{\"type\":\"fixed\", \"name\":\"n57\",  \"size\":4} },"
            + "  { \"name\":\"f2441em_MSR_LEVEL\", \"type\":{\"type\":\"fixed\", \"name\":\"n58\",  \"size\":1} },"
            + "  { \"name\":\"f2441em_RF_REF\", \"type\":{\"type\":\"fixed\", \"name\":\"n59\",  \"size\":25} },"
            + "  { \"name\":\"f2441em_PRIORITY\", \"type\":{\"type\":\"fixed\", \"name\":\"n60\",  \"size\":2} }"
            + "]}";

    public static final String AVRO_SCHEMA_f2441hm =
            "{"
            + "\"type\":\"record\","
            + "\"name\":\"f2441em\","
            + "\"fields\":["
            + "  { \"name\":\"f2441hm_PARTITION_OF_TABLE\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_ACCOUNT_OF_PAYER\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_PRESENT_TIMESTAMP\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_OWNER_APPLICATION\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_APPL_SPECIFIER\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_ORIGIN_OF_PAYMENT\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_STATUS_OF_PAYMENT\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_STATUS_SPECIFIER\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_STATUS_DATE\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_ACCOUNT_OF_PAYEE\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_NAME_OF_PAYEE\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_DUE_DATE\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_DATE_OF_PAYMENT\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_AMOUNT_OF_PAYMENT\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_CURRENCY_CODE\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_EMU_INDICATOR\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_CUSTOM_MODIF_RIGHT\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_SOLO_USER_ID\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_DISPOSAL_TYPE\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_REPEATING_RULE\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_PCS_OF_REPEATS\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_INVOICING_INFO\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_ORIGINAL_KEY\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_PAYMENT_SUBJECT\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_ARCHIV_SLIP_NUMBER\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_UPDATE_TIME_STAMP\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_REFERENCE_NUMBER\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_MESSAGE_INFO\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_DEBIT_RETURN_CODE\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_DEBIT_ARCHIV_NUMB\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_CREDIT_RETURN_CODE\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_CREDIT_ARCHIV_NUMB\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_PAYEE_ACCOUNT_TYPE\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_PAYEE_NAME_ORIGIN\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_REPEATING_DAYS\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_REPEATING_PERIOD\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_END_DATE_OF_REPEAT\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_REPEAT_CHANGE_INFO\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_INHERITANCE_INFO\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_BALANCE_OFFICE\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_ACCT_RESP_OFFICE\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_DUE_DATE_TYPE\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_PAYERS_RECEIPT\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_PAYEES_RECEIPT\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_USERS_CARD_NUMBER\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_CUSTOMER_ROLE\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_CONTROL_CODE\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_SOLO_AGR_TYPE\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_AMOUNT_LIMIT_CHECK\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_DEBTOR_ID\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_DEBTOR_ID_CODE\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_CREDITOR_BIC\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_CREDITOR_NAME\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_END_TO_END_ID\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_ULTIMATE_CREDITOR\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_ULTIMATE_DEBTOR\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_UR_TEXT_CODE\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_MSR_LEVEL\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_RF_REF\", \"type\":\"string\" },"
            + "  { \"name\":\"f2441hm_PRIORITY\", \"type\":\"string\" }"
            + "]}";

    public static final String AVRO_SCHEMA_f2441su =
            "{"
            + "\"type\":\"record\","
            + "\"name\":\"f2441su\","
            + "\"fields\":["
            + "  { \"name\":\"fico_field_1\", \"type\":\"string\" }"
            + "]}";
    public static final String AVRO_SCHEMA_f2441ve =
            "{"
            + "\"type\":\"record\","
            + "\"name\":\"f2441ve\","
            + "\"fields\":["
            + "  { \"name\":\"fico_field_1\", \"type\":\"string\" }"
            + "]}";
    public static final String AVRO_SCHEMA_f2441vh =
            "{"
            + "\"type\":\"record\","
            + "\"name\":\"f2441vh\","
            + "\"fields\":["
            + "  { \"name\":\"fico_field_1\", \"type\":\"string\" }"
            + "]}";
    public static final String AVRO_SCHEMA_f2441ya =
            "{"
            + "\"type\":\"record\","
            + "\"name\":\"f2441ya\","
            + "\"fields\":["
            + "  { \"name\":\"fico_field_1\", \"type\":\"string\" }"
            + "]}";
    public static final String AVRO_SCHEMA_f2441yp =
            "{"
            + "\"type\":\"record\","
            + "\"name\":\"f2441yp\","
            + "\"fields\":["
            + "  { \"name\":\"fico_field_1\", \"type\":\"string\" }"
            + "]}";

    public static final String AVRO_SCHEMA_t3330bb =
            "{"
            + "\"type\":\"record\","
            + "\"name\":\"t3330bb\","
            + "\"fields\":["
            + "  { \"name\":\"fico_field_1\", \"type\":\"string\" }"
            + "]}";

}
